#!/bin/zsh
#---------------ICONS----------------#
#icons => atribuir o nome dos programas sem hífen '-' , exemplo telegram-desktop fica telegramdesktop
#para pesquisar como um programa se chama ao adicioná-lo, use o seu id (disponivel em /tmp/taskbar) para pesquisar com
#xwinfo -i <id>, isso retornará a classe instancia da janela que será usado como o nome do programa.

export titlefontfocused="8"
export colorfontfocused=$color16

fontprogramicon=2
coloriconprg=$color2
fontworkspaceicon=3
coloriconwkp=$color2

reddit="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
twitter="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
github="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
linkedin="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
pulsemixer="%{F$coloriconprg}%{T$fontprogramicon}蓼%{F-}%{T-}"
WiFiAudio="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
htop="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
Netflix="%{F$coloriconprg}%{T$fontprogramicon}ﱄ%{F-}%{T-}"
xterm="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
kitty="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
termite="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
qutebrowser="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
firefox="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
pulseaudioequalizergtk="%{F$coloriconprg}%{T$fontprogramicon}蓼%{F-}%{T-}"
nitrogen="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
subl3="%{F$coloriconprg}%{T$fontprogramicon}﬏%{F-}%{T-}"
pamacmanager="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
tradutor="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
Steam="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
manjarosettingsmanager="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
thunar="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
ranger="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
nemo="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
nmconnectioneditor="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
nvidiasettings="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
qt5ct="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
lxappearance="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
color="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
oomox="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
arandr="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
telegramdesktop="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
whatsappnativefierd52542="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
smplayer="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
mpv="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
gl="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
xviewer="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
pavucontrol="%{F$coloriconprg}%{T$fontprogramicon}蓼%{F-}%{T-}"
strike="%{F$coloriconprg}%{T$fontprogramicon}𥳐%{F-}%{T-}"
csgo_linux64="%{F$coloriconprg}%{T$fontprogramicon}𥳐%{F-}%{T-}"
simplescreenrecorder="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
spyder="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
python="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
libreoffice="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
youtube="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
YouTube="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
spankbang="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
vim="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
gcolor2="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
codeoss="%{F$coloriconprg}%{T$fontprogramicon}﬏%{F-}%{T-}"
yad="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
gimp2="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
xreader="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
epdfview="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
pcmanfm="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
qtwebflix="%{F$coloriconprg}%{T$fontprogramicon}𥳐%{F-}%{T-}"
feh="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
gucharmap="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
Navigator="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
MozillaFirefox="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
Firefox="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
googlechrome="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
Alacritty="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
Mail="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
DBeaver="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
default="%{F$coloriconprg}%{T$fontprogramicon}%{F-}%{T-}"
# ícones que serão usados para representar os workspaces;
w1="%{F$coloriconwkp}%{T$fontworkspaceicon}%{F-}%{T-}"
w2="%{F$coloriconwkp}%{T$fontworkspaceicon}%{F-}%{T-}"
w3="%{F$coloriconwkp}%{T$fontworkspaceicon}%{F-}%{T-}"
w4="%{F$coloriconwkp}%{T$fontworkspaceicon}%{F-}%{T-}"
w5="%{F$coloriconwkp}%{T$fontworkspaceicon}%{F-}%{T-}"
w6="%{F$coloriconwkp}%{T$fontworkspaceicon}%{F-}%{T-}"
w7="%{F$coloriconwkp}%{T$fontworkspaceicon}%{F-}%{T-}"
w8="%{F$coloriconwkp}%{T$fontworkspaceicon}%{F-}%{T-}"
w9="%{F$coloriconwkp}%{T$fontworkspaceicon}%{F-}%{T-}"
w10="%{F$coloriconwkp}%{T$fontworkspaceicon}%{F-}%{T-}"
# ícones que serão usados para representar os workspaces em módulo separado;
W0=
W1=
W2=
W3=
W4=
W5=
W6=
W7=
W8=
W9=